### ISSUE TITLE
When will the code be open sourced?

### ISSUE THREAD

**Issue by ctxya1207** [Coobiw/IP-IQA#1]

**Comment by Coobiw** [comment]
Several days in this month. Thanks for your attention!

**Comment by ctxya1207** [comment]
the two databases are both split randomly in an 80/20 ratio for training/testing while ensuring the image with the same object label falls into the same set in the paper,I would like to know how to achieve this process

**Comment by Coobiw** [comment]
Hi, the code has been open-sourced. You can get it at [AGIQA-1k split function](https://github.com/Coobiw/IP-IQA/blob/master/train_agiqa1k.py#L69) and [AGIQA-3k split function](https://github.com/Coobiw/IP-IQA/blob/master/train_agiqa3k.py#L69). 
Thank you for your attention!

**Comment by Coobiw** [comment]
solved. I'll close this issue.
